FROM ubuntu

RUN apt-get update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y python3-pip python3-opencv vim-tiny libopencv-dev mosquitto-clien$

RUN pip3 install paho-mqtt

WORKDIR /
COPY cloud_saving.py .

CMD python cloud_saving.py

