FROM ubuntu

RUN apt-get update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y software-properties-common
RUN apt-get install -y python3-pip python3-opencv vim-tiny mosquitto-clients libopencv-dev
RUN pip3 install paho-mqtt
RUN pip3 install numpy

WORKDIR /
COPY face_detection.py .

CMD python3 face_dectection.py
